### PR TITLE
Social Media: Milestone six

### PR DESCRIPTION
**Pull request by brugobi**
## the milestone feature:

- [x] we can invite another user as a friend;
- [x] the user can accept or reject the invitation;
- [x] as soon the user accept an invitation the user can not invite the same friend twice;

### thank you for the review

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @brugobi and @emiliocm9, great job building this project :+1: However, before we can approve the project, we need to address the comments below: :smile: 

- The App could not run on my system after `bundle install`ing, I couldn't run `rails db:migrate`. Let us fix it
- There is not available test in the project, let us add test
- The README file is missing the following:
  - No authors name was recorded under the `Authors` section
  - The `getting started` section is missing a detailed instruction about how to clone the project. 

Kindly fix these and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by brugobi** [comment]
### thank you for your review

- about the error you got It might be because the project is using a pg as a database, so make sure you have Postgres: >=9.5 installed before migrate;
- The README file is not complete yet because it is part of the next milestone, so we will make all the changes on the next one.

[x] we add the tests are on the user_rspec.rb file inside the spec folder

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello!:wave: Nice job:+1: But we need to improve friendship as required for this milestone:**

:point_right: When a friendship is confirmed, a reverse pair should be created. You can achieve this with a method like this in your friendship model
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
or you can refactor your current confirm_friend method in User model to create the reverse pair.

:point_right: With the reverse pair been created, you can now use associations like the ones below to retrieve a user's friends.
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
**this is more efficient than using enumerable methods to retrieve the friends**

:point_right: You can retrieve a user's friend_requests with associations like this:
```ruby
# User model

has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

:point_right: And you can retrieve a user's pending friends with this:
```ruby
# User model

has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

:point_right: Timeline posts should include only posts by a user and his friends and not all posts. You can retrieve this with a method in your User model like this:
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

:point_right: You should have a button to send friend requests from a single user's page in addition to the all users page.

:point_right: Please extract all logic from your views into helper methods. Check your application layout, post index and users index views.

:point_right: Please add integration tests for all your features.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes.
However, there are some missed requirements and issues

1. As a requirement, [read it here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), Posts timeline includes posts written by logged-in user and their friends. It's not what is happening in your web application. Please, fix it.

2. As **say by the last reviewer**, You should have a button to send friend requests from a single user's page in addition to the all users page. It's a requirement that you can check [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png)

3. After sending a friendship request, there is no button to **accept it**
Take a look at this screenshot
Screenshot at 2020-08-21 23:26:32
You can notice that there is only a button to Decline the friendship. (Which is working very well)

4- Please, is indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png), that you must write **unit tests** and **integration tests**
For the unit tests, please, use the **Shoulda-matcher** gem

5- Don't forget to apply the changes suggested in the last reviews. There are really important.

Once changes applied, kindly submit a new code review request
Thanks

Mael FOSSO

**Comment by emiliocm9** [comment]
### Thank you for taking the time to review this project.

For this code review, we have made the next changes on our project:

- [x] We have fixed the issue with the Accept button, to accept a friendship invitation.
- [x] We have implemented unit tests (using Shoulda-matcher gem) and integration tests for every model used in the project.
- [x] We update the Heroku application.
- [x] Now we have a button to send, accept, or decline friend requests from a single user's page.
- [x] We implemented changes on the Timeline to display general posts, my friend's posts, and my posts (you have to create new friendship relations to be able to see your friend's posts, otherwise you will only see general posts and my posts) in different sections.

I would like to comment on this line because my partner and I have checked the images attached to the last reviews and it looks like there is a misunderstanding. Most of the milestones of this project are deprecated, therefore we are not supposed to make any changes on the scaffolds for likes, posts, users neither comments. These models have been made previously by the TSE's and we had to fork the project and work from there to develop the friendship model. As it seems that you haven't updated the requirements images on your GitLab support page since 8 months ago, I would like to suggest to make changes on every milestone specification because there's nothing related to change the Timeline or use Shoulda-matcher gem. Anyway, I think, it was very good to learn how to use the gem and make more changes, but would be better if you specify that in the Microverse Pathwright, so students could know that they have to accomplish these requirements before submitting a code review form.
DeprecatedMicro

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @brugobi @emiliocm9  :wave:
-
- You have done a splendid job with the changes! :tada: Keep it up.
- Everything is shaping up just one final round of tweaks and we should be good here (see review comment).
##
- [x] There is a bug in our code. I noticed that when a third user (not friends with the other two) is signed in, they also can see the first user's posts. Kindly, this might be an edge case and we need to fix this before we proceed. users should only view other users posts in which they are friends. Let's employ our skills gained from the members-only project here. Find inspiration here: 👉 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

- [x] I noticed you included in the project's readme, the instructions to run tests. The project, however, lacks test suites to runs. Kindly make sure we have proper tests suites for all our models, controller files and views to make it look more professional. Thank you.
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Review by trekab — APPROVED** [review]
## Approved! :tada: 
Well done working on the feedback from all the earlier reviewers! :clap: You may proceed to the last milestone. 

_Keep up the good work!_ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
